### ISSUE TITLE
BGS Tally crash report following Odyssey events

### ISSUE THREAD

**Issue by cluster-fox** [tezw21/BGS-Tally-Comguard#6]
Uncaught exception with Odyssey:

Chain of events:

**Location**

`{ "timestamp":"2021-12-11T12:45:31Z", "event":"Location", "Docked":true, "StationName":"Michael Enterprise", "StationType":"Coriolis", "MarketID":3222517760, "StationFaction":{ "Name":"Bahpu Citizen Party", "FactionState":"Election" }, "StationGovernment":"$government_Communism;", "StationGovernment_Localised":"Communist", "StationServices":[ "dock", "autodock", "blackmarket", "commodities", "contacts", "exploration", "missions", "outfitting", "crewlounge", "rearm", "refuel", "repair", "shipyard", "tuning", "engineer", "missionsgenerated", "flightcontroller", "stationoperations", "powerplay", "searchrescue", "stationMenu", "shop", "socialspace", "bartender", "vistagenomics", "pioneersupplies", "apexinterstellar", "frontlinesolutions" ], "StationEconomy":"$economy_Industrial;", "StationEconomy_Localised":"Industrial", "StationEconomies":[ { "Name":"$economy_Industrial;", "Name_Localised":"Industrial", "Proportion":1.000000 } ], "StarSystem":"Kaupolis", "SystemAddress":9467583735249, "StarPos":[50.87500,-203.78125,99.81250], "SystemAllegiance":"Independent", "SystemEconomy":"$economy_Industrial;", "SystemEconomy_Localised":"Industrial", "SystemSecondEconomy":"$economy_Military;", "SystemSecondEconomy_Localised":"Military", "SystemGovernment":"$government_Communism;", "SystemGovernment_Localised":"Communist", "SystemSecurity":"$SYSTEM_SECURITY_medium;", "SystemSecurity_Localised":"Medium Security", "Population":3603647, "Body":"Michael Enterprise", "BodyID":68, "BodyType":"Station", "Factions":[ { "Name":"Natural Kaupolis Order", "FactionState":"None", "Government":"Dictatorship", "Influence":0.048951, "Allegiance":"Empire", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":0.000000 }, { "Name":"People's Kaupolis Resistance", "FactionState":"None", "Government":"Democracy", "Influence":0.107892, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":0.000000 }, { "Name":"Bahpu Citizen Party", "FactionState":"Election", "Government":"Communism", "Influence":0.353646, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":100.000000, "ActiveStates":[ { "State":"Election" } ] }, { "Name":"Kaupolis Gold Comms Systems", "FactionState":"None", "Government":"Corporate", "Influence":0.039960, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":0.000000 }, { "Name":"Kaupolis Gold Mafia", "FactionState":"None", "Government":"Anarchy", "Influence":0.009990, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":0.000000 }, { "Name":"Cameron's Combat Services", "FactionState":"Election", "Government":"Cooperative", "Influence":0.353646, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "SquadronFaction":true, "HappiestSystem":true, "MyReputation":100.000000, "ActiveStates":[ { "State":"Expansion" }, { "State":"Election" } ] }, { "Name":"League of Kaupolis Nationalists", "FactionState":"None", "Government":"Dictatorship", "Influence":0.085914, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":0.000000 } ], "SystemFaction":{ "Name":"Bahpu Citizen Party", "FactionState":"Election" }, "Conflicts":[ { "WarType":"election", "Status":"active", "Faction1":{ "Name":"Bahpu Citizen Party", "Stake":"Michael Enterprise", "WonDays":0 }, "Faction2":{ "Name":"Cameron's Combat Services", "Stake":"Fawcett Installation", "WonDays":0 } } ] }`

**Docked**

`{ "timestamp":"2021-12-11T12:56:56Z", "event":"Docked", "StationName":"Fawcett Installation", "StationType":"CraterOutpost", "StarSystem":"Kaupolis", "SystemAddress":9467583735249, "MarketID":3506935552, "StationFaction":{ "Name":"Cameron's Combat Services", "FactionState":"Election" }, "StationGovernment":"$government_Cooperative;", "StationGovernment_Localised":"Cooperative", "StationServices":[ "dock", "autodock", "blackmarket", "commodities", "contacts", "exploration", "missions", "outfitting", "crewlounge", "rearm", "refuel", "repair", "engineer", "missionsgenerated", "flightcontroller", "stationoperations", "powerplay", "searchrescue", "stationMenu", "shop", "socialspace", "bartender", "vistagenomics", "pioneersupplies", "apexinterstellar", "frontlinesolutions" ], "StationEconomy":"$economy_Military;", "StationEconomy_Localised":"Military", "StationEconomies":[ { "Name":"$economy_Military;", "Name_Localised":"Military", "Proportion":1.000000 } ], "DistFromStarLS":322.086986 }
`

**Fail on marketSell**

`2021-12-11 06:59:14.351 - ERROR - 16372:12808:12808 plug.notify_journal_entry:272: Plugin "BGS Tally" failed
Traceback (most recent call last):
  File "plug.pyc", line 269, in notify_journal_entry
  File "%AppData%\Local\EDMarketConnector\plugins\BGS-Tally-Comguard-1.2.0\load.py", line 266, in journal_entry
    t = len(this.TodayData[this.DataIndex.get()][0]['Factions'])
KeyError: 1`

**Comment by cluster-fox** [comment]
**MarketSell** event

`{ "timestamp":"2021-12-11T12:57:25Z", "event":"MarketSell", "MarketID":3506935552, "Type":"thermalcoolingunits", "Type_Localised":"Thermal Cooling Units", "Count":128, "SellPrice":4601, "TotalSale":588928, "AvgPricePaid":3132 }`

**Comment by cluster-fox** [comment]
Possible culprit :

TickCheck on event "Docked"

`if this.LastTick.get() != this.CurrentTick:
            this.LastTick.set(this.CurrentTick)
            this.YesterdayData = this.TodayData
            this.TodayData = {}
            this.TimeLabel = tk.Label(this.frame, text=tick_format(this.TickTime)).grid(row=3, column=1, sticky=tk.W)
            theme.update(this.frame)
`

That effectively seems to empty the array on a new tick. 
In which case a FSDJump, CarrierJump or Location event is needed to rebuild the system list.

**Comment by cluster-fox** [comment]
Attempt at steps to reproduce (need to test over 2 days) :

- Prepare BGS action such as exploration Data.
- Close the game in target system, undocked
- Start the game after a tick
- Dock
- Do the BGS action
